import "./globals.css";
import type { Metadata } from "next";

import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="text-white">
      <body className="antialiased">
        <div className="flex flex-col items-center h-screen w-full bg-dark overflow-auto">
          <Header />
          <div className="flex-1 container">{children}</div>
        </div>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/styles/github-dark.min.css"
        ></link>
      </body>
    </html>
  );
}
